<?php
    $pcaSettings = $this->helper('PCAPredict\Addressy\Helper\SettingsData');
    $pcaAccCode = $pcaSettings->getAccountCode();

    if ($pcaAccCode) { 
?>

<script type="text/javascript">

    requirejs(['jquery'], function(){

        (function() {
            if (typeof pca !== "undefined") {
                pca.magento.setupCheckout();
            }
        })();
    });
  
</script>

<?php }
